### ISSUE TITLE
command yo classical-ko:page  <newComponentName>

### ISSUE THREAD

**Issue by Wenish** [ErikSvaleng/generator-classical-ko#6]
When u use this command it creates the line which is needed for register the compenent not correct

as example if u run:
`yo classical-ko:page test`

in the components.config.js it creates the code like this
`// [Scaffolded pages will be inserted here. To retain this feature, don't remove this comment.]        { name: 'test', path: 'pages/test/test' },`

for fix this problem it needs an extra linebreak

@ErikSvaleng i think its and easy fix or is it just on my client? (tested it with newst update)

**Comment by Wenish** [comment]
i saw its a problem with both commands(page and component)

**Comment by ErikSvaleng** [comment]
Hi Wenish! As always: thank you for all your contributions. Sorry for the late reply, I've been very busy lately. So I've reproduced this consistently on my Linux laptop, but inconsistently on my windows desktop. No idea why. I'm submitting a super simple bugfix that just inserts \n\t\t in the new line to create, and hoping this will work on all platforms. Tested working on Linux at least.

**Comment by Wenish** [comment]
thanks ;)
